In [1]:
##LINEAR SVM

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import datasets,svm
import matplotlib.pyplot as plt



In [2]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
col=['petal_length','petal_width']
df.loc[:,col].head()
X=df.loc[:,col]

In [6]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
species_to_num={'setosa':0,
                'versicolor':1,
                'virginica':2}

In [12]:
df['tmp']=df['species'].map(species_to_num)
Y=df['tmp']


Y


0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: tmp, Length: 150, dtype: int64

In [33]:
C = 0.001
clf = svm.SVC(kernel='linear', C=C)
#clf = svm.LinearSVC(C=C, loss='hinge')
#clf = svm.SVC(kernel='poly', degree=3, C=C)
#clf = svm.SVC(kernel='rbf', gamma=0.7, C=C)
clf.fit(X, y)

SVC(C=0.001, kernel='linear')

In [34]:
X

petal_length  petal_width
0             1.4          0.2
1             1.4          0.2
2             1.3          0.2
3             1.5          0.2
4             1.4          0.2
..            ...          ...
145           5.2          2.3
146           5.0          1.9
147           5.2          2.0
148           5.4          2.3
149           5.1          1.8

[150 rows x 2 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [13]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.8,random_state=0)

In [14]:
sc_x=StandardScaler()
x_std_train=sc_x.fit_transform(x_train)

In [41]:
c=1
clf=svm.SVC(kernel='linear',C=c)
clf.fit(x_std_train,y_train)

SVC(C=1, kernel='linear')

In [17]:
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.metrics import precision_score,recall_score,f1_score,confusion_matrix

In [47]:
res=cross_val_score(clf,x_std_train,y_train,cv=10,scoring='accuracy')
print(np.mean(res))
np.std(res)


0.95


0.055277079839256664

In [49]:
y_train_pred=cross_val_predict(clf,x_std_train,y_train,cv=3)
y_train_pred

array([2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 0, 1,
       1, 2, 1, 0, 0, 0, 2, 1, 2, 0], dtype=int64)

In [50]:
confusion_matrix(y_train,y_train_pred)

array([[39,  0,  0],
       [ 0, 34,  3],
       [ 0,  3, 41]], dtype=int64)

In [55]:
print(precision_score(y_train,y_train_pred,average='weighted'))
print(recall_score(y_train,y_train_pred,average='weighted'))
print(f1_score(y_train,y_train_pred,average='weighted'))

0.95
0.95
0.95


In [56]:
y_test_pred=cross_val_predict(clf,sc_x.transform(x_test),y_test,cv=3)

In [58]:
confusion_matrix(y_test,y_test_pred)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  2,  4]], dtype=int64)

In [59]:
print("Precision Score: \t {0:.4f}".format(precision_score(y_test, 
                                                           y_test_pred, 
                                                           average='weighted')))
print("Recall Score: \t\t {0:.4f}".format(recall_score(y_test,
                                                     y_test_pred, 
                                                     average='weighted')))
print("F1 Score: \t\t {0:.4f}".format(f1_score(y_test,
                                             y_test_pred, 
                                             average='weighted')))

Precision Score: 	 0.9422
Recall Score: 		 0.9333
F1 Score: 		 0.9290


In [63]:
c=1.0
clf=svm.SVC(kernel='poly',C=c,degree=3)
clf.fit(X,Y)

SVC(kernel='poly')

In [64]:
clf=svm.SVC(kernel='poly',C=c,degree=10,gamma='auto')
clf.fit(x_std_train,y_train)

SVC(degree=10, gamma='auto', kernel='poly')

In [65]:
res=cross_val_score(clf,x_train,y_train,cv=10,scoring='accuracy')

In [68]:
print(np.mean(res))
print(np.std(res))

0.9499999999999998
0.04082482904638632


In [71]:
y_train_pred=cross_val_predict(clf,x_std_train,y_train,cv=3)
confusion_matrix(y_train,y_train_pred)

array([[35,  0,  4],
       [ 0, 37,  0],
       [ 7, 18, 19]], dtype=int64)

In [72]:
print("Precision Score: \t {0:.4f}".format(precision_score(y_train, 
                                                           y_train_pred, 
                                                           average='weighted')))
print("Recall Score: \t\t {0:.4f}".format(recall_score(y_train,
                                                     y_train_pred, 
                                                     average='weighted')))
print("F1 Score: \t\t {0:.4f}".format(f1_score(y_train,
                                             y_train_pred, 
                                             average='weighted')))

Precision Score: 	 0.7812
Recall Score: 		 0.7583
F1 Score: 		 0.7368


In [74]:
y_test_pred=cross_val_predict(clf,sc_x.transform(x_test),y_test,cv=3)
confusion_matrix(y_test,y_test_pred)

array([[10,  0,  1],
       [ 0, 13,  0],
       [ 3,  3,  0]], dtype=int64)

In [75]:
print("Precision Score: \t {0:.4f}".format(precision_score(y_test, 
                                                           y_test_pred, 
                                                           average='weighted')))
print("Recall Score: \t\t {0:.4f}".format(recall_score(y_test,
                                                     y_test_pred, 
                                                     average='weighted')))
print("F1 Score: \t\t {0:.4f}".format(f1_score(y_test,
                                             y_test_pred, 
                                             average='weighted')))

Precision Score: 	 0.6341
Recall Score: 		 0.7667
F1 Score: 		 0.6941


In [15]:
c=1
clf=svm.SVC(kernel='rbf',gamma=0.7,C=c)
clf.fit(x_std_train,y_train)

SVC(C=1, gamma=0.7)

In [20]:
res=cross_val_score(clf,x_std_train,y_train,cv=10,scoring='accuracy')
np.mean(res)
np.std(res)

0.055277079839256664

In [21]:
y_train_pred=cross_val_predict(clf,x_std_train,y_train,cv=3)
confusion_matrix(y_train,y_train_pred)

array([[39,  0,  0],
       [ 0, 35,  2],
       [ 0,  3, 41]], dtype=int64)

In [22]:
print("Precision Score: \t {0:.4f}".format(precision_score(y_train, 
                                                           y_train_pred, 
                                                           average='weighted')))
print("Recall Score: \t\t {0:.4f}".format(recall_score(y_train,
                                                     y_train_pred, 
                                                     average='weighted')))
print("F1 Score: \t\t {0:.4f}".format(f1_score(y_train,
                                             y_train_pred, 
                                             average='weighted')))

Precision Score: 	 0.9586
Recall Score: 		 0.9583
F1 Score: 		 0.9584


In [32]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV,train_test_split

In [33]:
pipeline=Pipeline([('clf',svm.SVC(kernel='rbf',C=1,gamma=0.1))])

In [34]:
params = {'clf__C':(0.1, 0.5, 1, 2, 5, 10, 20), 
          'clf__gamma':(0.001, 0.01, 0.1, 0.25, 0.5, 0.75, 1)} 

In [35]:
svm_grid_rbf=GridSearchCV(pipeline,params,n_jobs=-1,cv=3,verbose=1,scoring='accuracy')

In [37]:
svm_grid_rbf.fit(x_train,y_train)

Fitting 3 folds for each of 49 candidates, totalling 147 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done 147 out of 147 | elapsed:    2.7s finished


GridSearchCV(cv=3, estimator=Pipeline(steps=[('clf', SVC(C=1, gamma=0.1))]),
             n_jobs=-1,
             param_grid={'clf__C': (0.1, 0.5, 1, 2, 5, 10, 20),
                         'clf__gamma': (0.001, 0.01, 0.1, 0.25, 0.5, 0.75, 1)},
             scoring='accuracy', verbose=1)

In [40]:
best=svm_grid_rbf.best_estimator_.get_params()
best

{'memory': None,
 'steps': [('clf', SVC(C=0.5, gamma=0.5))],
 'verbose': False,
 'clf': SVC(C=0.5, gamma=0.5),
 'clf__C': 0.5,
 'clf__break_ties': False,
 'clf__cache_size': 200,
 'clf__class_weight': None,
 'clf__coef0': 0.0,
 'clf__decision_function_shape': 'ovr',
 'clf__degree': 3,
 'clf__gamma': 0.5,
 'clf__kernel': 'rbf',
 'clf__max_iter': -1,
 'clf__probability': False,
 'clf__random_state': None,
 'clf__shrinking': True,
 'clf__tol': 0.001,
 'clf__verbose': False}

In [41]:
for k in sorted(params.keys()): 
    print('\t{0}: \t {1:.2f}'.format(k, best[k]))

	clf__C: 	 0.50
	clf__gamma: 	 0.50


In [4]:
from sklearn.datasets import load_boston
import pandas as pd
boston_data=load_boston()
df=pd.DataFrame(boston_data.data,columns=boston_data.feature_names)

In [5]:
X=df[['LSTAT']].values
Y=boston_data.target

In [10]:
from sklearn.svm import SVR
svr=SVR(gamma='auto')
from sklearn.model_selection import train_test_split
svr.fit(X,Y)

SVR(gamma='auto')

In [9]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [13]:
svr=SVR(kernel='linear')
svr.fit(x_train,y_train)

SVR(kernel='linear')

In [20]:
y_train_pred=svr.predict(x_train)
y_test_pred=svr.predict(x_test)
from sklearn.metrics import mean_squared_error,r2_score

In [22]:
print(mean_squared_error(y_train,y_train_pred))
print(mean_squared_error(y_test,y_test_pred))



41.81871766364949
36.83721464991496


In [23]:
print(r2_score(y_train,y_train_pred))
print(r2_score(y_test,y_test_pred))

0.5242278854168403
0.5056276434474074
